### ISSUE TITLE
Allow require()'s to be commented out

### ISSUE THREAD

**Issue by johntron** [tj/node-requires#2]
Currently, `requires()` uses this regular expression to find dependencies: `/require *\(['"]([^'"]+)['"]\)/g;` This matches `require()`'s that are commented-out.

**Comment by tj** [comment]
yea there's a few edge-cases, require()s in strings etc, but it's worth the simplicity/perf tradeoff for 99% of cases

**Comment by johntron** [comment]
Agreed, I think the only decent solution would be to lex the files, but that's a ton of added overhead and dependencies.

I ran into this using builder2.js on a component with no dependencies and this on the first line: `// var History = require('history');`

**Comment by tj** [comment]
yeah substack already has one for that but it's verrrrrry rarely necessary

**Comment by tj** [comment]
but also if it's commented out it shouldn't matter at all

**Comment by johntron** [comment]
Unless it's not in the `component.json` and you're trying to build :P I'll see if I can add an error message to builder2.js for this edge-case, because it would be really difficult to debug if you haven't read this issue.
